apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation-system-settings
data:
  DEBUG: "True"
  ALLOWED_HOSTS: "*"
  POSTGRES_DB: "mydatabase"
  POSTGRES_USER: "postgres"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  REDIS_LOCATION: "redis://redis-0.redis.recommendation-system.svc.cluster.local/1"
  # Foo: "BAR"
# "NAME": os.getenv("POSTGRES_DB", "yourdatabase"),
#         "USER": os.getenv("POSTGRES_USER", "yourusername"),
#         "PASSWORD": os.getenv("POSTGRES_PASSWORD", "yourpassword"),
#         "HOST": os.getenv("POSTGRES_HOST", "localhost"),
#         "PORT": os.getenv("POSTGRES_PORT", "5432"),