apiVersion: ENC[AES256_GCM,data:Klc=,iv:jmAGlRreRTT0HzWL+0+9DqJhU2srq/oI1CL7i/ZOO+0=,tag:HpVIbEoUnTywOUXrWya3+A==,type:str]
kind: ENC[AES256_GCM,data:yXsdvNmj,iv:Re6ZoUmslnOErQBPYaDST8zxGzQ0Gpb+3fDF+slD/uw=,tag:QCgAvlijjbb3gdn/wOwV0g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:s/733iGOf0DPBV+IxR65Gyhw44gIDYJ148gV3xQ=,iv:T7MixNL7WQV7iqYUKjKtfRZMJJ2aIjtS2wBTE23DSbc=,tag:Slsc9JmvRTO3zybKJpfnwg==,type:str]
type: ENC[AES256_GCM,data:9Rh1GipK,iv:kBir3QME+e/ayB2fLVhUGENFwA8sW5qMcrl0366fl6Y=,tag:DmFdmP/m4fCn2KC9MWCQuQ==,type:str]
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:ygXG6CISEWUpmktrKG2u,iv:VhJFu4hI3nGdInnmSNB62ivv/BBAbPRDoHkn0wmAJPk=,tag:z2f5FAgEplLOuxkN9F3OHA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:PCtL7lA2WoQMgQE2mgLh5A==,iv:H5a+mCQrHZd0ey5pSTC0/B4GQ8187zHidM1an2uhFG0=,tag:nud+4+ow62Jr+9d44xj9/A==,type:str]
sops:
    lastmodified: "2026-03-27T22:22:02Z"
    mac: ENC[AES256_GCM,data:PoZydBH27F4SNQUqQTagWczNcVqW9kZiiaBos0jbJBTz+7RVR1XMQGpgYU08Er7LyN4+ZIXWFhqrhI2xF4xTzyeJdpXxrcFgTNcYO14QVBmTibaERHlAlO1tUR2SzHhIjQXKbyOGKZINe4XuGjJ+zg+1DtrgpHHQD3Z2Mmpee3w=,iv:1BnuMCWeonUNmmMnF6xripcnejUMOwiEmRO/BSSdtro=,tag:75EoNTuAvnnXx941fpXwjw==,type:str]
    pgp:
        - created_at: "2026-03-27T22:22:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA/t+fE/QSiqAAQwAv+NTtf8lqFr595d3KCSM8IWinGhhu9K6KsZqUv9sqjEW
            U3BFrAxXr7E3weOGMHRs3YWScaow0YLFh6w+xXtxDVf/W4d+QYAWaVfKG8y76j9h
            dLiwp1K38+J98SP3Nv479Ud0dhDEdA+HpmShXjjziBw2bK5nbQQYkp0lU7XbpdxX
            sW3j0S6oONBpMIYkfbg90YFpoqCddlQ+SOeoirSxN5RaGFsg59TXqKx3YSOmDCEp
            fWe9At8KcrkPFfIthXw9QWSaMyPie8jRpLZSbFcejr3d6cgEu0sWDxNtqwfsfnnR
            COwaBkC8yXynAox7ElopNKC/AWkbfCNIi+QNCEZX6e3OClkZfzftVuwmxCosllFr
            94WWtm7a3SL2zm1jX05NbheNHS1y2oTBwzOUUESperZQD1wHde2DRqbQMJLqQHKK
            Q8haUXx0xrXJA/tObpGuW28nNjufBoTpDvIYk+AvDB2SZKWLOfXJ8pRm9LdmvTpw
            yb8jzeH5EO/QWDaI7hKK1GgBCQIQGCo/169lDwZnQ+Pdkqm+N0XroP2vECS89nFO
            zX0S/hV7TJbXMKvuh9EufH7Lc0auvDPQZJDPT1y5io7a19859AzrnYr7jtUAjO8O
            +DHGNLUrvnwODxPPMvYO8uTz+lYeF+4fOg==
            =GyQ5
            -----END PGP MESSAGE-----
          fp: E407C0985045B3983D57846B8EDE307FF8EF1658
    unencrypted_suffix: _unencrypted
    version: 3.12.2
