# Generated by Django 6.0 on 2025-12-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
