# Generated by Django 6.0 on 2025-12-20 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="year",
        ),
        migrations.AddField(
            model_name="movie",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="extra_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="movie",
            name="release_year",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1888),
                    django.core.validators.MaxValueValidator(2025),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="movie",
            constraint=models.UniqueConstraint(
                fields=("title", "country", "release_year"), name="unique_movie"
            ),
        ),
    ]
