# Generated by Django 6.0 on 2026-01-31 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_usermoviepreferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_year",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1888),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
    ]
