# Generated by Django 6.0 on 2026-02-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_alter_movie_release_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="country",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
