# Generated by Django 6.0 on 2026-02-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_alter_movie_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="country",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
